//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleEnergy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnergyEntities : DbContext
    {
        public EnergyEntities()
            : base("name=EnergyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Город> Город { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Книга> Книга { get; set; }
        public virtual DbSet<Корзина_Заказа> Корзина_Заказа { get; set; }
        public virtual DbSet<Курьер> Курьер { get; set; }
        public virtual DbSet<Покупатель> Покупатель { get; set; }
    }
}
