//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleEnergy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Корзина_Заказа = new HashSet<Корзина_Заказа>();
        }
    
        public int Код_заказа { get; set; }
        public long Код_покупателя { get; set; }
        public string Форма_оплаты { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public string Тип_доставки { get; set; }
        public double Цена_доставки { get; set; }
        public Nullable<int> Код_курьера { get; set; }
        public string Адрес_доставки { get; set; }
        public Nullable<int> Код_города { get; set; }
    
        public virtual Город Город { get; set; }
        public virtual Курьер Курьер { get; set; }
        public virtual Покупатель Покупатель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Корзина_Заказа> Корзина_Заказа { get; set; }
    }
}
