//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleEnergy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Корзина_Заказа
    {
        public int Код_заказа { get; set; }
        public int Код_книги { get; set; }
        public int Количество_в_заказе { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Книга Книга { get; set; }
    }
}
